### ISSUE TITLE
Loaders Do Not Work: traverse is not a function.

### ISSUE THREAD

**Issue by barziahmed** [universal-future/vxrn#355]
If I add the loader to my index page, like this:

```
import { Image } from '@tamagui/image-next'
import { Text, YStack } from 'tamagui'
import oneBall from '~/public/app-icon.png'
import { useLoader } from 'one'

export async function loader() {
  return {
    user: 'tamagui'
  }
}

export  function HomePage() {
  const data = useLoader(loader)

	return (
		<YStack
			bg='$color1'
			mih='100%'
			gap='$4'
			ai='center'
			jc='center'
			f={1}
		>
			<Text fontSize={20}>Hello,     {data.user}</Text>
			<Image
				src={oneBall}
				width={128}
				height={128}
			/>
		</YStack>
	)
}
```

I will get the following error:

```
[vite] program reload
[vite] An error happened during full reload
[vite] cannot find entry point module 'virtual:one-entry'.
Error: [vite] cannot find entry point module 'virtual:one-entry'.
    at <anonymous> (/Users/panda/Desktop/monorepo/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:51428:13)
    at processTicksAndRejections (native)
 🪄 app/index.tsx
24 |     referenced = findReferencedIdentifiers(ast),
25 |     removed = {
26 |       loader: !1,
27 |       generateStaticParams: !1
28 |     };
29 |   traverse(ast, {
       ^
TypeError: traverse is not a function. (In 'traverse(ast, {
    ExportNamedDeclaration(path) {
      if (path.node.declaration && path.node.declaration.type === "FunctionDeclaration") {
        if (!path.node.declaration.id)
          return;
        const functionName = path.node.declaration.id.name;
        (functionName === "loader" || functionName === "generateStaticParams") && (path.remove(), removed[functionName] = !0);
      } else
        path.node.declaration && path.node.declaration.type === "VariableDeclaration" && path.node.declaration.declarations.forEach((declarator, index) => {
          if (declarator.id.type === "Identifier" && (declarator.id.name === "loader" || declarator.id.name === "generateStaticParams")) {
            const declaration = path.get("declaration.declarations." + index);
            Array.isArray(declaration) || (declaration.remove(), removed[declarator.id.name] = !0);
          }
        });
    }
  })', 'traverse' is undefined)
      at /Users/panda/Desktop/monorepo/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:29:3
      at transformTreeShakeClient (/Users/panda/Desktop/monorepo/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:17:3)
      at /Users/panda/Desktop/monorepo/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:15:37
      at transform (/Users/panda/Desktop/monorepo/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:14:21)
      at /Users/panda/Desktop/monorepo/node_modules/vite/dist/node/chunks/dep-0AosnpPU.js:47220:19
      at processTicksAndRejections (native:1:1)

Bun v1.1.42 (macOS arm64)
error: script "dev" exited with code 1

I use one version 1.1.375, with react 19.

**Comment by natew** [comment]
what starter template / what platform / how can we repro?

**Comment by lukeshay** [comment]
@natew Just started trying out this framework and I am having the same issue. I am using the tamagui starter and just added a loader to `app/index.tsx` and got the same error.

**Comment by gyulavoros** [comment]
I bumped into this issue as well, using Bun 1.2.19 and One 1.1.506.

**Comment by zetavg** [comment]
Hi @gyulavoros @lukeshay - thanks for providing the info, but unfortunately I'm unable to reproduce the issue using `npx one`, Minimal Tamagui, and `bun`.

Tried with Node.js versions `22.17.1`, `20.18.0`, and `24.3.0`.

`jq .version node_modules/@babel/traverse/package.json` shows `"7.28.0"`.

Could you share your Node.js version, along with your `package.json` and `bun.lock` files to help troubleshoot further?

**Comment by gyulavoros** [comment]
Hi @zetavg, thank you for looking into this!

Here's an example project for repro: [hello-world.zip](https://github.com/user-attachments/files/21465443/hello-world.zip)

Please note, that I use `bun --bun run dev` to run the project ([--bun](https://bun.sh/docs/cli/run#bun)). Running `bun run dev` works. I had the assumption that without the `--bun` flag, Vite would actually use Node to run the project, but I've just checked the Activity Monitor, and it doesn't seem to be the case. 🤔

Hope it helps to investigate!

<img width="1770" height="1026" alt="Image" src="https://github.com/user-attachments/assets/9889e9f4-ffcb-48c5-9cf8-6536a5b71ab4" />

This was the project setup:
```
bunx one
warn: incorrect peer dependency "vite@7.0.6"

warn: incorrect peer dependency "vite@7.0.6"

warn: incorrect peer dependency "react-native@0.80.2"

warn: incorrect peer dependency "react@19.0.0"

  Hello. Let's create a new ①  app...

✔ Name … hello-world


✔ Template › Minimal

⠙ Creating...


hello-world created!


✔ Package Manager: › bun


Installing with bun...

bun install v1.2.19 (aad3abea)
warn: incorrect peer dependency "vite@7.0.6"

warn: incorrect peer dependency "@expo/metro-config@0.20.17"

warn: incorrect peer dependency "vite@7.0.6"

+ @react-native-community/cli@19.0.0
+ @types/react@18.3.23 (v19.1.8 available)
+ vite@7.0.6
+ expo@53.0.20
+ one@1.1.510
+ react@19.0.0 (v19.1.0 available)
+ react-native@0.79.5 (v0.80.2 available)
+ react-native-reanimated@3.19.0 (v4.0.0 available)
+ react-native-safe-area-context@5.4.1
+ react-native-screens@4.10.0
+ react-native-web@0.20.0 (v0.21.0 available)

1026 packages installed [3.43s]

Blocked 3 postinstalls. Run `bun pm untrusted` for details.
bun install completed successfully.

Done! Created a new project under ./hello-world
```

This is how I run the project:
```
bun --bun run dev
$ one dev
[vite] connected.
10:58:05 AM [vite] (client) Re-optimizing dependencies because vite config has changed
10:58:05 AM [vite] (ssr) Re-optimizing dependencies because vite config has changed

Server running on ⪢

  ➜  Local:   http://localhost:8081/
  ➜  Network: http://192.168.1.112:8081/

› Press ow │ open web
› Press oi │ open app in iOS Simulator
› Press oa │ open app in Android Emulator
› Press oe │ open editor
› Press qr │ show Expo Go QR code
› Press dt │ open React Native DevTools
› Press ?  │ show this menu

 ⓵  [ssg] http://localhost:8081/ resolved to app/index.tsx
10:58:08 AM [vite] Internal server error: traverse is not a function. (In 'traverse(ast, {
    ExportNamedDeclaration(path) {
      if (path.node.declaration && path.node.declaration.type === "FunctionDeclaration") {
        if (!path.node.declaration.id)
          return;
        const functionName = path.node.declaration.id.name;
        (functionName === "loader" || functionName === "generateStaticParams") && (path.remove(), removed[functionName] = !0);
      } else
        path.node.declaration && path.node.declaration.type === "VariableDeclaration" && path.node.declaration.declarations.forEach((declarator, index) => {
          if (declarator.id.type === "Identifier" && (declarator.id.name === "loader" || declarator.id.name === "generateStaticParams")) {
            const declaration = path.get("declaration.declarations." + index);
            Array.isArray(declaration) || (declaration.remove(), removed[declarator.id.name] = !0);
          }
        });
    }
  })', 'traverse' is undefined)
  Plugin: one-client-tree-shake
  File: /Users/gyulavoros/Downloads/temp/hello-world/app/index.tsx:33:3
      at transformTreeShakeClient (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:33:3)
      at transformTreeShakeClient (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:22:41)
      at handler (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:18:134)
      at handler (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/one/dist/esm/vite/plugins/clientTreeShakePlugin.mjs:17:21)
      at transform (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:31274:51)
      at transform (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:31256:18)
      at loadAndTransform (/Users/gyulavoros/Downloads/temp/hello-world/node_modules/vite/dist/node/chunks/dep-BHkUv4Z8.js:26451:48)
      at processTicksAndRejections (native:7:39)
```

**Comment by natew** [comment]
I think this is likely more a bun issue than our issue, in that they have different module resolution. Does it work on the latest bun now? We don't support `bun --bun` atm, I'm adding that to the docs. If someone wants to help contribute happy to accept it!

**Comment by gyulavoros** [comment]
@natew with the latest bun (`1.2.20`), it still doesn't work, but there's a different error:

```
bun --bun dev
$ one dev
[vite] connected.
✘ [ERROR] Could not resolve "@babel/runtime/helpers/interopRequireDefault"

    ../../.bun/install/cache/react-native-web@0.21.0@@@1/dist/cjs/index.js:3:37:
      3 │ var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/helpers/interopRequireDefault" as external to exclude it
  from the bundle, which will remove this error and leave the unresolved path in the bundle. You can
  also surround this "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "@babel/runtime/helpers/interopRequireDefault"

    ../../.bun/install/cache/react-native-web@0.21.0@@@1/dist/cjs/exports/ProgressBar/index.js:13:37:
      13 │ var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;
         ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/helpers/interopRequireDefault" as external to exclude it
  from the bundle, which will remove this error and leave the unresolved path in the bundle. You can
  also surround this "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

✘ [ERROR] Could not resolve "@babel/runtime/helpers/interopRequireDefault"

    ../../.bun/install/cache/react-native-web@0.21.0@@@1/dist/cjs/exports/createElement/index.js:13:37:
      13 │ var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;
         ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/helpers/interopRequireDefault" as external to exclude it
  from the bundle, which will remove this error and leave the unresolved path in the bundle. You can
  also surround this "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.

...
```

And it continues for ~9000 lines.
